#!/bin/sh
#
# Generate a new signature file.
#
# Usage: siggen mail.jar mail.sig
#
SIGTEST=${SIGTEST:-/java/re/sigtest/2.2/promoted/opensource/latest/binaries/sigtest-2.2}
SIGTEST_JAR=$SIGTEST/lib/sigtestdev.jar
JAF_JAR=${JAF_JAR:-$HOME/ext/activation.jar}
JAVA_HOME=${JAVA_HOME:-/opt/jdk1.4}
PKG=javax.mail
USAGE="siggen [-p package] mail.jar mail.sig"

while getopts p: opt
do
	case $opt in
	p)	PKG="$OPTARG";;
	\?)	echo $USAGE; exit 1;;
	esac
done
shift `expr $OPTIND - 1`

${JAVA_HOME}/bin/java -jar $SIGTEST_JAR setup -static \
	-classpath "$1:${JAVA_HOME}/jre/lib/rt.jar:${JAVA_HOME}/jre/lib/jsse.jar:$JAF_JAR" \
	-filename "$2" -package "$PKG" -nonclosedfile
