#!/bin/sh
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010-2017 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://oss.oracle.com/licenses/CDDL+GPL-1.1
# or LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.
#

#
# Generate a new signature file.
#
# Usage: siggen javax.mail.jar mail.sig
#
SIGTEST=${SIGTEST:-/java/re/sigtest/4.0/promoted/fcs/latest/binaries/sigtest-4.0}
SIGTEST_JAR=$SIGTEST/lib/sigtestdev.jar
JAVA_HOME=${JAVA_HOME:-/opt/jdk1.8}
PKG=javax.mail
USAGE="siggen [-p package] javax.mail.jar mail.sig"

while getopts p: opt
do
	case $opt in
	p)	PKG="$OPTARG";;
	\?)	echo $USAGE; exit 1;;
	esac
done
shift `expr $OPTIND - 1`

ver=$($JAVA_HOME/bin/java -version 2>&1 | sed -e 's/.*"\(.*\)".*/\1/;q')
case "$ver" in
1.[0-9]*)	xjimage=;
		cp="$1:${JAVA_HOME}/jre/lib/rt.jar:${JAVA_HOME}/jre/lib/jce.jar";;
*)		xjimage="-xjimage ${JAVA_HOME}/bin/jimage";
		cp="$1:${JAVA_HOME}/lib/modules";;
esac

${JAVA_HOME}/bin/java -jar $SIGTEST_JAR setup -static \
	-classpath "$cp" $xjimage \
	-filename "$2" -package "$PKG" -nonclosedfile
