#!/bin/sh
#
# Compare API against a signature file.
#
# Usage: sigtest mail.jar mail.sig
#
SIGTEST=${SIGTEST:-/java/re/sigtest/2.2/promoted/opensource/latest/binaries/sigtest-2.2}
APICHECK_JAR=$SIGTEST/lib/apicheck.jar
JAF_JAR=${JAF_JAR:-$HOME/ext/activation.jar}
JAVA_HOME=${JAVA_HOME:-/opt/jdk1.4}
USAGE="sigtest [-b] [-p package] mail.jar mail.sig"
PKG=javax.mail
BACKWARD=

while getopts bp: opt
do
	case $opt in
	p)	PKG="$OPTARG";;
	b)	BACKWARD=-backward;;
	\?)	echo $USAGE; exit 1;;
	esac
done
shift `expr $OPTIND - 1`

${JAVA_HOME}/bin/java -jar $APICHECK_JAR -static \
	-classpath "$1:${JAVA_HOME}/jre/lib/rt.jar:${JAVA_HOME}/jre/lib/jsse.jar:$JAF_JAR" \
	-filename "$2" -package "$PKG" -out /dev/stdout \
	-nomerge -checkvalue -mode src "$BACKWARD"
